#----------------------------------------------------------------------
# This file was generated by C:\Users\Sizov\AppData\Local\Programs\Python\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

apply = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAB05J'
    b'REFUWIXFl1tsXEcZx38zc87Z9fru2HEcO/cmacOSFoc0TZOURAq4bSiBqgKkij7AQ6VCERKv'
    b'CIlHQLwRLg9FSC0FtYCa0Cq0hVIVQZqoiZpmQ+zETmrHjdu49saX9e7ZMzMfD7t2kq7TRlzU'
    b'OVrNWc053/8y35z5Rilt+Dib/ljRgeBmH5Qu10OWLaygj5BeDFkC6gGwFHDkSDjBRV4kx3E1'
    b'ZkZvJq76qCmQ5a6O9XyVLI/RSva21RvTm7tup6e5h9ZMKwD5uTznJy9wdvwMp4f7S0yS4xQ/'
    b'4xy/U5dM8T8iIN5p9nMX6/jV0u6OjZ+/cx993fexNN2BiCDINVFAodBoLseXefGdP/P8sed5'
    b'b3R8gCG+zkFeV9r4xXCMUjdIg/3yMGs5cPf2bese3f4oe5btITAGKxYrFlf9+WpvxZJIQqQj'
    b'Ptm6mVu7b2W2brp9pDC6l07G1YB+66YIVJTLw6nN0ZP7dt/b8u3e79AUNhJLjPMeT4L1FUAv'
    b'FiseKwleLIlYHJZYElqjZu5ZsZti82zLcDL8YNKSDHFGckpp+VACfEG2q3Uc2L1zV8uXN3wF'
    b'Lw6HQ7zFKY/3FlGCx+PwVEb9wmW9x0tCWcrErsSG1g1M113h/NSFLXRwVJ3VF29IQJa7OrVL'
    b'HV55x/J139z8LbRSeCzWe0RZnPc4ZfG+otyJRZStPmNx4nAkaKXZs2wvnelOLhaH2dS2iVPu'
    b'zZapeHanjPgn1Iy2izuwVb5Wf0f0jb5sHysbVi1oFPF45RDlEREcHnTFCSceJx5RHo/FqICt'
    b'7Xexqn41rVEbTixjpTFU6BmcHmwvT9ghNazfrCEgXa5H7eYnt2xduXzH0l2kgqiSaFUSCyZr'
    b'C8rjpELIK4uoSh4YZdjbeS+rG9ZWoivoquumPqhnrPgOY6mLjM9MdstFOaxm9TRc+yXMsqWh'
    b'K51tDBqIdEjiyzhJWN+4EdEeh8WrBO8dCQme+d6SSBmjNHe172B5puf6nFKwsfk2ti/dScZk'
    b'aOzJZMmyZX74KoFV9GU6Uun6qJ5AGwJjeKD7S3yu6352d+ytAPkYq8pYYhLKeGISiTEK+jof'
    b'4NbG7CILDWaSaS7MnacpzNDQmU6zir5aAil6U5kQwTHnZ9jZ8RnWNNwCwKamzWxp24ZXFbWV'
    b'KUlIJMEoxY72PXRnVi4KXnYxf7n8AmPFEUQL6UwIKXrnxxf2Al1HNpUJCIOAzy67n0+1br3O'
    b'xrvbdtMUNvHS+EGsCEopUjpiX+dDrKhbewPwEs9eepKh2UHKEuOkTCYTEtSRdR90wATUR5Fh'
    b'ZWYVn16yvTaagmxjL9tad+GVw2jDPUvuuyF47Eq8NH6IwUI/KMesm6ZEiSgKMaGqr3FAKUVo'
    b'Qk5MHeWngz/ku+u/j1KqhsSO1r3UBw00h22sqduwOLgv8cx7TzBU6Ee0AS+MlUdAWcIwuC7u'
    b'ggNipaBEEQUBB9/9LYff+yNeFtk/FNzeuO1DwV+a+AODc6cRBULCnC+Qt+8TBiFYcIkUagjY'
    b'MjlJpLICtOHnIz/iqdFfLEqixpl5cFfkmfFf8sbsayjjEZVQkBnejvvRGgKtwQquLLlaB+Y4'
    b'4UueQGuM1jjKHBp/ipcnnlvciRrwEi9OPctQfAptwCuHJebdZARLmVBrAmNIig5f4sT8e1c/'
    b'xUskSC03X+zoaQ5CU1kNSgm5uaMU/DSbG+7kRlt37Es8e+UA/yodQ2mNJaFgZ7hsL2HFopTC'
    b'A0rB6LmJUv5A4QeqqIeuc4Acx8fensoFQcUBXXVCB5pXpp7jhfxvcN4tAl7k5ZmnOZ+cQhmI'
    b'ZZoZP8ksV9BGEVZjhVoRhgGj5yZyRJyucUDN6mmXcjbsCva3L2skMgEmCIhMQGgM55KTzMgE'
    b'2fS2BSdiP8fTMz8mV/4HVsfEUiBRCSLuap6IVDvFuZNjXDqc/57KmddqpwAgkYFiT/mhrhUt'
    b'7ZlMilBVFARBQBQEjLkLhCZgTbiJspQ4XPw1Z+zrGKVRmgoxEbTWeO+rwIIHpq/McfLI2wPx'
    b'3+zjN9yO1Yy25bbkRL5Y2Ltm/dKWKBUSBBUHwqoTw+40Ba5wMnmFAX+UdJDCzE+XUguVoq8q'
    b'90A5trz6p9PD+VNzj6jj5sK1U1hbEfXLO6XWZLxkyg92r2gjFQVoYwiNwShNFEZclgsU9ARR'
    b'EBEYg9EV5SgF3jOfKR6hVLIceeUsF49MPs5BDn9kSaaUFjWg38qnZofG8vktK1YvaWloSGG0'
    b'IQwCAmOIgvDqvTFoXa0pqooRwSPkJwq88PvjwyP/nHhcHTJPfRB8cQfm2xnJzbWUj45OvL9T'
    b'PO2r13ZUstkYtKqs6aD6XwGuWqp7EbTRHPn7WV796+mBiTdnH1lM+TWCb+5g0nBn6rHbe9dk'
    b'N6xfll7S1siS1noydWmMMcRxwmR+lonJGfr7L5XeeGMwN3ss/u8OJjVEulwPc3yCh9nf3BT1'
    b'NjXWZVPpqF4B5TgpTE0Xc1fy8QnO/4+PZv/v9rGfjv8NX6ia5WofONoAAAAASUVORK5CYII=')

